language: node_js
node_js:
  - 10
install:
  - yarn config set ignore -engines true
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $blog
  keep_history: true
  on:
    branch: master
